modmap:
  - name: HHKB Meta to Alt for TUI emacs
    device:
      only: "HHKB-Hybrid_2 Keyboard"
    application:
      only: "com.mitchellh.ghostty"
    remap:
      KEY_LEFTMETA:
        held: KEY_LEFTALT
        alone: KEY_HANJA
        free_hold: true
      KEY_RIGHTMETA:
        held: KEY_LEFTALT
        alone: KEY_HANGEUL
        free_hold: true

  - name: HHKB Command tap/hold
    device:
      only: "HHKB-Hybrid_2 Keyboard"
    remap:
      KEY_LEFTMETA:
        held: KEY_LEFTMETA
        alone: KEY_HANJA
        free_hold: true
      KEY_RIGHTMETA:
        held: KEY_RIGHTMETA
        alone: KEY_HANGEUL
        free_hold: true

keymap:
  - name: Emacs key bind
    device:
      only: "HHKB-Hybrid_2 Keyboard"
    application:
      not: "com.mitchellh.ghostty"
    remap:
      C-A: Home
      C-E: End
      C-F: Right
      C-B: Left
      C-N: Down
      C-P: Up
      C-H: Backspace
      C-D: Delete
      C-K: [Shift-End, C-X]
      Super-X: C-X
      Super-C: C-C
      Super-V: C-V

  - name: Ghostty (Dependent on "Meta to Alt")
    device:
      only: "HHKB-Hybrid_2 Keyboard"
    application:
      only: "com.mitchellh.ghostty"
    remap:
      Alt-C: C-Shift-C
      Alt-V: C-Shift-V
